server:
  port: 8081
spring:
  application:
    name: reggie_take_out
    #应用的名称默认该项目名
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #Url要改成自己的jdbc:mysql://localhost:3306/reggie?serverTimezone=UTC
      # url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      url: jdbc:mysql://192.168.8.1:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    host: 192.168.8.130
    port: 6379
    password: yangroot
  cache:
    redis:
      time-to-live: 1800000 #设置缓存有效期

    lettuce:
      pool:
        max-active: 10 #最大连接数量
        max-idle: 10 #阻塞最大等待时间
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1 #操作的数据库1，这里默认是0,我的0做的其他项目缓存


  # 邮箱配置
  mail:
    host: smtp.qq.com  # 发送邮件的服务器地址
    username: 1573478674@qq.com # 开启 IMAP/SMTP服务 的qq邮箱的账号
    password: aibzoigxgvfphjjg # 开启 IMAP/SMTP服务 获得的授权码,而不是qq邮箱的登录密码
    default-encoding: UTF-8

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #比如表user_name > 对应表userName
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #    mapper-locations: classpath:mybatis/mapper/*.xml
    db-config:
      id-type: ASSIGN_ID

#设置一个外部配置源，输出的地址
reggie:
  path: /usr/local/img/